name: Run Mobile GUI Automated Tests

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths-ignore:
      - './github'
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    # environment: Testing
    env:
      APP: ${{ secrets.APP }}
      BS_USER: ${{ secrets.BS_USER }}
      BS_ACCESS_KEY: ${{ secrets.BS_ACCESS_KEY }}

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build -e app=${{ env.APP }} -e user=${{ env.BS_USER }} -e accessKey=${{ env.BS_ACCESS_KEY }}
    
    - name: Load test report history
      uses: actions/checkout@v4
      if: always()
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages

    - name: Build test report
      uses: simple-elf/allure-report-action@v1.9
      if: always()
      with:
        gh_pages: gh-pages
        allure_history: allure-history
        allure_results: MobileTests/bin/Debug/net8.0/allure-results

    - name: Publish test report
      uses: peaceiris/actions-gh-pages@v4
      if: always()
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: allure-history